"""
Backend Service - Alert Notification Microservice

This service consumes trading alerts from Kafka and sends push notifications
to mobile devices via Firebase Cloud Messaging (FCM).

Input: Kafka topic 'alert' with trading alert data
Output: Firebase Cloud Messaging notifications to subscribed users
"""
from kafka import KafkaConsumer
import json
import time
from pathlib import Path
import os
import logging

# Service configuration
MICROSERVICE_NAME = "backend"
USE_DUMMY_FIREBASE = os.getenv("USE_DUMMY_FIREBASE", "false").lower() == "true"

# Ensure logs directory exists
log_dir = Path("../logs")
log_dir.mkdir(parents=True, exist_ok=True)

# Configure logging for production
# Using 'a' (append) mode instead of 'w' to preserve logs across restarts
logging.basicConfig(
    level=logging.INFO,
    filename=f"../logs/{MICROSERVICE_NAME}.log",
    filemode="a",
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

logger = logging.getLogger(MICROSERVICE_NAME)
logger.info(f"Starting {MICROSERVICE_NAME} - Initializing Firebase and Kafka consumer")
logger.info(f"Using dummy Firebase: {USE_DUMMY_FIREBASE}")

# ============================================================================
# Firebase Initialization
# ============================================================================
# Initialize Firebase Admin SDK with service account credentials
# This enables sending push notifications via Firebase Cloud Messaging

try:
    if USE_DUMMY_FIREBASE:
        logger.warning("Using DUMMY Firebase - no real notifications will be sent")
        import dummy_firebase as firebase_admin
        from dummy_firebase import credentials
        cred_path = "dummy-credentials.json"
    else:
        import firebase_admin
        from firebase_admin import credentials
        cred_path = "firebase-admin-key.json"
        
    if not Path(cred_path).exists():
        logger.error(f"Firebase credentials file not found: {cred_path}")
        if not USE_DUMMY_FIREBASE:
             raise FileNotFoundError(f"Firebase credentials file not found: {cred_path}")
    
    cred = credentials.Certificate(cred_path)
    firebase_admin.initialize_app(cred)
    logger.info(f"Firebase Admin SDK ({'Dummy' if USE_DUMMY_FIREBASE else 'Real'}) initialized successfully")
    
    from send_message import send_data_message
except Exception as e:
    logger.error(f"Failed to initialize Firebase: {str(e)}", exc_info=True)
    raise

# ============================================================================
# Kafka Consumer Configuration
# ============================================================================
# Consume trading alerts from Kafka topic 'alert'
# These alerts are generated by the decision service when significant
# market movements are predicted
logger.info("Configuring Kafka consumer for topic 'alert'")
kafka_broker = os.getenv("KAFKA_BROKER", "localhost:9092")
max_retries = 30
retry_delay = 2
consumer = None

for attempt in range(max_retries):
    try:
        consumer = KafkaConsumer(
            "alert",
            bootstrap_servers=kafka_broker,
            group_id="math-group",
            auto_offset_reset="latest",
            enable_auto_commit=True,
            value_deserializer=lambda v: json.loads(v.decode("utf-8"))
        )
        logger.info("Kafka consumer configured successfully")
        break
    except Exception as e:
        if attempt < max_retries - 1:
            logger.warning(f"Kafka not available (attempt {attempt+1}/{max_retries}): {str(e)}. Retrying in {retry_delay}s...")
            time.sleep(retry_delay)
        else:
            logger.error(f"Failed to connect to Kafka after {max_retries} attempts: {str(e)}", exc_info=True)
            raise

# ============================================================================
# Main Processing Loop
# ============================================================================
# Continuously consume alerts and send push notifications
logger.info("Starting alert processing loop - waiting for messages...")
try:
    for msg in consumer:
        data = msg.value
        logger.info(f"Received alert message: {json.dumps(data, indent=2)}")
        
        try:
            # Send push notification via Firebase Cloud Messaging
            res = send_data_message(data)
            logger.info(f"Alert notification sent successfully. Message ID: {res}")
            print(f"Alert sent: {res}")
        except Exception as e:
            logger.error(
                f"Failed to send alert notification: {str(e)} | "
                f"Alert data: {json.dumps(data)}",
                exc_info=True
            )
            # Continue processing other messages even if one fails
            continue
except KeyboardInterrupt:
    logger.info("Alert processing interrupted by user")
except Exception as e:
    logger.error(f"Fatal error in alert processing loop: {str(e)}", exc_info=True)
    raise
finally:
    if consumer:
        consumer.close()
        logger.info("Kafka consumer closed")
    