"""
Backend Service - Alert Notification Microservice

This service consumes trading alerts from Kafka and sends push notifications
to mobile devices via Firebase Cloud Messaging (FCM).

Input: Kafka topic 'alert' with trading alert data
Output: Firebase Cloud Messaging notifications to subscribed users
"""
from kafka import KafkaConsumer, KafkaProducer
import json
import time
from pathlib import Path
import os
import logging

# Service configuration
MICROSERVICE_NAME = "backend"
USE_DUMMY_FIREBASE = os.getenv("USE_DUMMY_FIREBASE", "false").lower() == "true"

# Ensure logs directory exists
log_dir = Path("../logs")
log_dir.mkdir(parents=True, exist_ok=True)

# Configure logging for production
# Using 'a' (append) mode instead of 'w' to preserve logs across restarts
logging.basicConfig(
    level=logging.INFO,
    filename=f"../logs/{MICROSERVICE_NAME}.log",
    filemode="a",
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

logger = logging.getLogger(MICROSERVICE_NAME)
logger.info(f"Starting {MICROSERVICE_NAME} - Initializing Firebase and Kafka consumer")
logger.info(f"Using dummy Firebase: {USE_DUMMY_FIREBASE}")

# Initialize Observability Telemetry
from infra.telemetry_client import TelemetryClient, ClickHouseLogHandler
telemetry = TelemetryClient()

# Set up ClickHouse Centralized Log Harvesting (Warning/Error/Fatal)
ch_handler = ClickHouseLogHandler(service_name=MICROSERVICE_NAME)
ch_handler.setFormatter(logging.Formatter(fmt="%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
logging.getLogger().addHandler(ch_handler)
logger.info("Centralized ClickHouse logging telemetry registered successfully")

# Start Container System Resource Telemetry Daemon
try:
    from infra.system_daemon import start_system_daemon
    start_system_daemon(MICROSERVICE_NAME)
    logger.info("System Resource Telemetry Daemon started successfully")
except Exception as e:
    logger.warning(f"Failed to start System Resource Telemetry Daemon: {e}")


# ============================================================================
# Firebase Initialization
# ============================================================================
# Initialize Firebase Admin SDK with service account credentials
# This enables sending push notifications via Firebase Cloud Messaging

try:
    if USE_DUMMY_FIREBASE:
        logger.warning("Using DUMMY Firebase - no real notifications will be sent")
        import dummy_firebase as firebase_admin
        from dummy_firebase import credentials
        cred_path = "dummy-credentials.json"
    else:
        import firebase_admin
        from firebase_admin import credentials
        cred_path = "firebase-admin-key.json"
        
    if not Path(cred_path).exists():
        logger.error(f"Firebase credentials file not found: {cred_path}")
        if not USE_DUMMY_FIREBASE:
             raise FileNotFoundError(f"Firebase credentials file not found: {cred_path}")
    
    cred = credentials.Certificate(cred_path)
    firebase_admin.initialize_app(cred)
    logger.info(f"Firebase Admin SDK ({'Dummy' if USE_DUMMY_FIREBASE else 'Real'}) initialized successfully")
    
    from send_message import send_data_message
except Exception as e:
    logger.error(f"Failed to initialize Firebase: {str(e)}", exc_info=True)
    raise

# ============================================================================
# Kafka Consumer Configuration
# ============================================================================
# Consume trading alerts from Kafka topic 'alert'
# These alerts are generated by the decision service when significant
# market movements are predicted
logger.info("Configuring Kafka consumer for topic 'alert'")
kafka_broker = os.getenv("KAFKA_BROKER", "localhost:9092")
max_retries = 30
retry_delay = 2
consumer = None

for attempt in range(max_retries):
    try:
        consumer = KafkaConsumer(
            bootstrap_servers=kafka_broker,
            group_id="math-group",
            auto_offset_reset="latest",
            enable_auto_commit=True,
            value_deserializer=lambda v: json.loads(v.decode("utf-8"))
        )
        consumer.subscribe(["alert", "alert_retry"])
        logger.info("Kafka consumer subscribed to 'alert' and 'alert_retry' successfully")
        break
    except Exception as e:
        if attempt < max_retries - 1:
            logger.warning(f"Kafka not available (attempt {attempt+1}/{max_retries}): {str(e)}. Retrying in {retry_delay}s...")
            time.sleep(retry_delay)
        else:
            logger.error(f"Failed to connect to Kafka after {max_retries} attempts: {str(e)}", exc_info=True)
            raise

# Producer: Send failed alerts to retry or DLQ topics
logger.info("Configuring Kafka producer for retry and DLQ")
producer = None
for attempt in range(max_retries):
    try:
        producer = KafkaProducer(
            bootstrap_servers=[kafka_broker],
            value_serializer=lambda v: json.dumps(v).encode('utf-8')
        )
        logger.info("Kafka producer for retry/DLQ configured successfully")
        break
    except Exception as e:
        if attempt < max_retries - 1:
            logger.warning(f"Kafka not available for producer (attempt {attempt+1}/{max_retries}): {str(e)}. Retrying in {retry_delay}s...")
            time.sleep(retry_delay)
        else:
            logger.error(f"Failed to connect Kafka producer after {max_retries} attempts: {str(e)}", exc_info=True)
            raise
# ============================================================================
# Main Processing Loop
# ============================================================================
# Continuously consume alerts and send push notifications
logger.info("Starting alert processing loop - waiting for messages...")

MAX_RETRIES = 3

try:
    for msg in consumer:
        data = msg.value
        topic = msg.topic
        logger.info(f"Received message from topic '{topic}': {json.dumps(data, indent=2)}")
        print(f"Received from '{topic}': {data.get('symbol')}")

        try:
            # Send push notification via Firebase Cloud Messaging
            start_fcm = time.time()
            res = send_data_message(data)
            end_fcm = time.time()
            fcm_push_delay = (end_fcm - start_fcm) * 1000
            
            # Log FCM latency
            telemetry.log_latency(
                service_name=MICROSERVICE_NAME,
                symbol=data.get("symbol", "UNKNOWN"),
                metric_name="fcm_push_delay",
                latency_ms=fcm_push_delay,
                cycle=data.get("cycle", 0)
            )
            
            logger.info(f"Alert notification sent successfully. Message ID: {res}")
            print(f"✓ Alert sent for {data.get('symbol')}: {res}")
        except Exception as e:
            error_msg = str(e)
            logger.error(
                f"Failed to send alert notification: {error_msg} | "
                f"Alert data: {json.dumps(data)}",
                exc_info=True
            )

            # Retrieve and increment retry count
            retry_count = data.get("retry_count", 0)
            
            if retry_count < MAX_RETRIES:
                retry_count += 1
                data["retry_count"] = retry_count
                data["last_error"] = error_msg
                
                # Small 1-second delay only during failure handling to prevent rapid spinning hot loops
                time.sleep(1)
                
                try:
                    logger.info(f"Routing alert for {data.get('symbol')} back to retry queue (Attempt {retry_count}/{MAX_RETRIES})")
                    producer.send("alert_retry", value=data)
                    producer.flush()
                    print(f"→ Routed {data.get('symbol')} to 'alert_retry' (Attempt {retry_count}/{MAX_RETRIES})")
                except Exception as pe:
                    logger.error(f"Failed to route message to retry topic: {str(pe)}")
            else:
                try:
                    logger.warning(f"Max retries ({MAX_RETRIES}) exceeded for {data.get('symbol')}. Routing to dead letter queue ('alert_dlq').")
                    data["final_error"] = error_msg
                    producer.send("alert_dlq", value=data)
                    producer.flush()
                    print(f"☠ CRITICAL: Sent {data.get('symbol')} to 'alert_dlq'")
                except Exception as pe:
                    logger.error(f"Failed to route message to DLQ topic: {str(pe)}")

            # Continue processing other messages
            continue
except KeyboardInterrupt:
    logger.info("Alert processing interrupted by user")
except Exception as e:
    logger.error(f"Fatal error in alert processing loop: {str(e)}", exc_info=True)
    raise
finally:
    if consumer:
        consumer.close()
        logger.info("Kafka consumer closed")
    