apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse_monitoring:8123
    password: password
    jsonData:
      defaultDatabase: telemetry
      username: default
      tlsSkipVerify: true
    isDefault: true
    editable: true
