apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse_monitoring:8123
    jsonData:
      defaultDatabase: telemetry
      username: default
      tlsSkipVerify: true
      timeout: 60
      server: clickhouse_monitoring
      port: 8123
      protocol: http
    secureJsonData:
      password: password
    isDefault: true
    editable: true
